### ISSUE TITLE
Add ability to fetch more than 1000 rows of data

### ISSUE THREAD

**Issue by kvncp** [adafruit/Adafruit_IO_Python#108]
The current implementation of the `data()` method only fetches a single page worth of data. This library should implement the pagination specification to allow multiple pages to be fetched.

Some thoughts on API options:
* Add a keyword argument to the `data()` method: `max_results=1000`. Setting this value to a larger number would trigger the retrieval of multiple pages of data, if they are available.
* Add a new method that can implement a more comprehensive API, including allowing things like specifying the start time, end time, etc for data to fetch.

I'd be happy to take a shot at implementation. The first option is probably the easiest to implement and shouldn't take much effort. Open to any thoughts or feedback on an API.

**Comment by lcmcninch** [comment]
I'd like to take a shot at implementing this and other [get feed data](https://io.adafruit.com/api/docs/?shell#get-feed-data) query parameters. I'm basically a noob when it comes to contributing to public projects. I suspect I'll have some questions when it comes to code style, how this project implements tests, etc. Is this issue an appropriate forum for that kind of discussion or is there a better place to discuss such topics?

Thanks!

**Comment by brentru** [comment]
@lcmcninch  We have a guide on the Adafruit Learning System about contributing (https://learn.adafruit.com/contribute-to-arduino-with-git-and-github) but it's geared towards our Arduino libraries rather than our Python libraries.

The applicable steps in this guide are:
- Grab Your Fork
- Always Work on a Branch
- Status, Add, Commit, Push
- Create Your Pull Request
- Open Pull Request

Tests are run automatically and code is checked with a linter (pylint) when you open a pull request. I'll be happy to review it and answer any questions w.r.t code style/etc in the pull request.
